from . import res_users
from . import res_partner
from . import res_currency
from . import res_lang
from . import res_company
from . import product_category
from . import product_product
from . import pos_category
from . import pos_tax
from . import pos_payment_method
from . import pos_payment
from . import pos_session
from . import pos_order
from . import pos_order_line
from . import pos_config
from . import delivery_zone
from . import stock_lot
from . import login_log
from . import inventory_item
from . import purchase_order
from . import purchase_item
from . import pending_product
from . import purchase_receipt
from . import purchase_receipt_item
from . import inventory_transaction
