import base64
import io
from datetime import datetime
from fpdf import FPDF
from ..odoo_orm import env
from ..models.pos_order import PosOrder
from ..models.pos_order_line import PosOrderLine
from ..models.pos_payment import PosPayment
from ..models.pos_payment_method import PosPaymentMethod
from ..models.res_company import ResCompany
from ..models.res_partner import ResPartner
from ..models.res_users import ResUsers
from ..models.product_product import ProductProduct
from ..models.res_currency import ResCurrency
from ..models.delivery_zone import DeliveryZone


def get_order_data(order_id):
    orders = PosOrder().browse([order_id])
    if not orders:
        return None
    order = orders[0]
    d = {'id': order.id, '_data': order._data}

    lines = PosOrderLine().search([('order_id', '=', order.id)])
    d['lines'] = []
    for line in lines:
        ld = {'_data': line._data}
        pid = line._data.get('product_id', 0) or 0
        pname = 'Product'
        if pid:
            product = ProductProduct().browse([pid])
            if product:
                pname = product[0]._data.get('name', 'Product')
        ld['product_name'] = pname
        d['lines'].append(ld)

    payments = PosPayment().search([('order_id', '=', order.id)])
    d['payments'] = []
    for pmt in payments:
        pd_data = {'_data': pmt._data}
        pmid = pmt._data.get('payment_method_id', 0) or 0
        pname = 'Cash'
        if pmid:
            method = PosPaymentMethod().browse([pmid])
            if method:
                pname = method[0]._data.get('name', 'Cash')
        pd_data['payment_method_name'] = pname
        d['payments'].append(pd_data)

    pid = order._data.get('partner_id', 0) or 0
    d['partner_name'] = '-'
    if pid:
        partner = ResPartner().browse([pid])
        if partner:
            d['partner_name'] = partner[0]._data.get('name', '-')

    uid = order._data.get('user_id', 0) or 0
    d['user_name'] = ''
    if uid:
        user = ResUsers().browse([uid])
        if user:
            d['user_name'] = user[0]._data.get('name', '')

    dzid = order._data.get('delivery_zone_id', 0) or 0
    d['delivery_zone_name'] = ''
    d['delivery_cost'] = float(order._data.get('delivery_cost', 0) or 0)
    d['delivery_contact_name'] = order._data.get('delivery_contact_name', '') or ''
    d['delivery_contact_phone'] = order._data.get('delivery_contact_phone', '') or ''
    if dzid:
        zone = DeliveryZone().browse([dzid])
        if zone:
            d['delivery_zone_name'] = zone[0]._data.get('name', '')

    company = ResCompany().search([], limit=1)
    d['company'] = company[0]._data if company else {}
    if company:
        cur_id = company[0]._data.get('currency_id', 0) or 0
        if cur_id:
            cur = ResCurrency().browse([cur_id])
            if cur:
                d['currency'] = cur[0]._data

    return d


def currency_format(amount, currency=None):
    if currency is None:
        currency = {}
    symbol = currency.get('symbol', 'FG')
    decimals = currency.get('decimal_places', 0)
    position = currency.get('position', 'before')
    formatted = f"{float(amount or 0):.{decimals}f}"
    if position == 'before':
        return f"{symbol} {formatted}"
    return f"{formatted} {symbol}"


RECEIPT_LABELS = {
    'en': {
        'receipt': 'RECEIPT',
        'order': 'Order',
        'status': 'Status',
        'date': 'Date',
        'cashier': 'Cashier',
        'customer': 'Customer',
        'item': 'Item',
        'qty': 'Qty',
        'price': 'Price',
        'total': 'Total',
        'subtotal': 'Subtotal',
        'discount': 'Discount',
        'payment': 'PAYMENT',
        'change': 'Change',
        'tel': 'Tel',
        'tax_id': 'Tax ID',
        'generated': 'Generated by Shop With DD POS',
        'print': 'Print',
        'close': 'Close',
        'delivery': 'Delivery',
    },
    'fr': {
        'receipt': 'REÇU',
        'order': 'Commande',
        'status': 'Statut',
        'date': 'Date',
        'cashier': 'Caissier',
        'customer': 'Client',
        'item': 'Article',
        'qty': 'Qté',
        'price': 'Prix',
        'total': 'Total',
        'subtotal': 'Sous-total',
        'discount': 'Remise',
        'payment': 'PAIEMENT',
        'change': 'Monnaie',
        'tel': 'Tél',
        'tax_id': 'NIF',
        'generated': 'Généré par Shop With DD POS',
        'print': 'Imprimer',
        'close': 'Fermer',
        'delivery': 'Livraison',
    },
}


def _(key, lang='en'):
    labels = RECEIPT_LABELS.get(lang, RECEIPT_LABELS['en'])
    return labels.get(key, RECEIPT_LABELS['en'].get(key, key))


def generate_receipt_html(order_id, lang='en'):
    d = get_order_data(order_id)
    if not d:
        return None

    data = d['_data']
    lines = d['lines']
    payments = d['payments']
    company = d['company']
    currency = d.get('currency', {})

    logo_html = ''
    if company.get('logo'):
        logo_html = f'<img src="data:image/png;base64,{company["logo"]}" class="receipt-logo">'

    items_rows = ''
    for line in lines:
        ld = line['_data']
        name = line['product_name']
        qty = float(ld.get('qty', 0) or 0)
        price = float(ld.get('price_unit', 0) or 0)
        disc = float(ld.get('discount', 0) or 0)
        subtotal = float(ld.get('price_subtotal', 0) or (qty * price * (1 - disc / 100)))
        items_rows += f'''<tr>
            <td style="padding:4px 0">{name}</td>
            <td style="text-align:center">{qty}</td>
            <td style="text-align:right">{currency_format(price, currency)}</td>
            <td style="text-align:right">{currency_format(subtotal, currency)}</td>
        </tr>'''

    payments_rows = ''
    for pmt in payments:
        pd = pmt['_data']
        pmt_name = pmt['payment_method_name']
        amt = float(pd.get('amount', 0) or 0)
        payments_rows += f'<tr><td>{pmt_name}</td><td style="text-align:right">{currency_format(amt, currency)}</td></tr>'

    date_val = (data.get('date_order', '') or '')[:19]
    total = float(data.get('amount_total', 0) or 0)
    delivery_cost = float(d.get('delivery_cost', 0) or 0)
    items_total = total - delivery_cost
    paid = float(data.get('amount_paid', 0) or 0)
    change = float(data.get('amount_change', 0) or 0)
    state = data.get('state', '')
    ref = data.get('name', '') or f"{_('order', lang)} #{d['id']}"

    delivery_contact_html = ''
    if d.get('delivery_contact_name') or d.get('delivery_contact_phone'):
        parts = []
        if d['delivery_contact_name']:
            parts.append(d['delivery_contact_name'])
        if d['delivery_contact_phone']:
            parts.append(d['delivery_contact_phone'])
        contact_str = ' - '.join(parts)
        dz_name = d.get('delivery_zone_name', '')
        delivery_contact_html = f'<div class="info-grid"><span><strong>{_("delivery", lang)}:</strong> {dz_name}</span></div><div class="info-grid"><span>{contact_str}</span></div>'

    html_lang = 'fr' if lang == 'fr' else 'en'

    return f'''<!DOCTYPE html>
<html lang="{html_lang}">
<head>
<meta charset="UTF-8">
<title>{_('receipt', lang)} - {ref}</title>
<style>
  @page {{ margin: 0; size: 80mm auto; }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Courier New', monospace; font-size: 12px; padding: 10px; color: #000; }}
  .receipt {{ max-width: 80mm; margin: 0 auto; }}
  .receipt-logo {{ max-width: 60mm; max-height: 30mm; display: block; margin: 6px auto; }}
  h2 {{ text-align: center; font-size: 14px; margin: 4px 0; }}
  .company-info {{ text-align: center; font-size: 11px; margin-bottom: 6px; }}
  .header-line {{ text-align: center; font-size: 16px; font-weight: bold; margin: 8px 0; letter-spacing: 2px; }}
  .divider {{ border-top: 1px dashed #000; margin: 6px 0; }}
  .info-grid {{ display: flex; justify-content: space-between; font-size: 11px; margin: 4px 0; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 11px; }}
  th {{ border-bottom: 1px solid #000; padding: 4px 0; text-align: left; }}
  td {{ padding: 2px 0; }}
  .totals-table td {{ border: none; padding: 2px 4px; }}
  .total-row {{ font-weight: bold; font-size: 13px; }}
  .footer {{ text-align: center; margin-top: 8px; font-size: 11px; }}
  .payment-info {{ margin-top: 6px; }}
  .status-badge {{ display: inline-block; padding: 2px 8px; border: 1px solid #000; font-weight: bold; font-size: 10px; }}
  @media print {{ body {{ padding: 10px; }} .no-print {{ display: none; }} }}
  .no-print {{ text-align: center; margin-top: 12px; }}
  .no-print button {{ padding: 8px 24px; font-size: 14px; cursor: pointer; background: #2563eb; color: #fff; border: none; border-radius: 4px; }}
</style>
</head>
<body>
<div class="receipt">
  {logo_html}
  <h2>{company.get('name', '')}</h2>
  <div class="company-info">
    {company.get('street', '') and company['street'] + '<br>'}
    {company.get('city', '') and company['city']}
    {company.get('state', '') and ', ' + company['state']}
    {company.get('zip_code', '') and ' ' + company['zip_code']}
    {company.get('country', '') and '<br>' + company['country']}
    {company.get('phone', '') and '<br>' + _('tel', lang) + ': ' + company['phone']}
    {company.get('email', '') and '<br>' + company['email']}
    {company.get('vat', '') and '<br>' + _('tax_id', lang) + ': ' + company['vat']}
  </div>

  <div class="divider"></div>
  <div class="header-line">{_('receipt', lang)}</div>
  <div class="divider"></div>

  <div class="info-grid">
    <span><strong>{_('order', lang)}:</strong> {ref}</span>
    <span><strong>{_('status', lang)}:</strong> <span class="status-badge">{state}</span></span>
  </div>
  <div class="info-grid">
    <span><strong>{_('date', lang)}:</strong> {date_val}</span>
  </div>
  <div class="info-grid">
    <span><strong>{_('cashier', lang)}:</strong> {d['user_name']}</span>
    <span><strong>{_('customer', lang)}:</strong> {d['partner_name']}</span>
  </div>
  {delivery_contact_html}

  <div class="divider"></div>
  <table>
    <thead>
      <tr><th style="width:40%">{_('item', lang)}</th><th style="width:15%;text-align:center">{_('qty', lang)}</th><th style="width:22%;text-align:right">{_('price', lang)}</th><th style="width:23%;text-align:right">{_('total', lang)}</th></tr>
    </thead>
    <tbody>
      {items_rows}
    </tbody>
  </table>
  <div class="divider"></div>

  <table class="totals-table">
    <tr><td style="text-align:right;width:70%">{_('subtotal', lang)}:</td><td style="text-align:right;width:30%">{currency_format(items_total, currency)}</td></tr>
    {delivery_cost > 0 and f'<tr><td style="text-align:right">{_("delivery", lang)}:</td><td style="text-align:right">{currency_format(delivery_cost, currency)}</td></tr>' or ''}
    <tr><td style="text-align:right">{_('discount', lang)}:</td><td style="text-align:right">{currency_format(0, currency)}</td></tr>
    <tr class="total-row"><td style="text-align:right">{_('total', lang).upper()}:</td><td style="text-align:right">{currency_format(total, currency)}</td></tr>
  </table>

  {company.get('receipt_header', '') and '<div class="divider"></div><div class="company-info">' + company['receipt_header'] + '</div>'}

  <div class="divider"></div>
  <div class="header-line" style="font-size:12px">{_('payment', lang)}</div>
  <table class="payment-info">
    {payments_rows}
    <tr><td>{_('change', lang)}:</td><td style="text-align:right">{currency_format(change, currency)}</td></tr>
  </table>

  {company.get('receipt_footer', '') and '<div class="divider"></div><div class="footer">' + company['receipt_footer'] + '</div>'}

  <div class="divider"></div>
  <div class="footer" style="font-size:9px">{_('generated', lang)} - {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>

  <div class="no-print">
    <button onclick="window.print()">{_('print', lang)}</button>
    <button onclick="window.close()">{_('close', lang)}</button>
  </div>
</div>
</body>
</html>'''


class ReceiptPDF(FPDF):
    def __init__(self):
        super().__init__(orientation='P', unit='mm', format=(80, 297))
        self.set_auto_page_break(auto=True, margin=5)

    def header(self):
        pass

    def footer(self):
        pass


def generate_receipt_pdf(order_id, lang='en'):
    d = get_order_data(order_id)
    if not d:
        return None

    data = d['_data']
    lines = d['lines']
    payments = d['payments']
    company = d['company']
    currency = d.get('currency', {})

    pdf = ReceiptPDF()
    pdf.add_page()
    pdf.set_margins(5, 5, 5)

    page_w = 80 - 10
    left = 5

    y = 5

    # Logo
    if company.get('logo'):
        try:
            img_data = base64.b64decode(company['logo'])
            img_fp = io.BytesIO(img_data)
            pdf.image(img_fp, x=left + page_w / 2 - 15, w=30, h=15)
            y = pdf.get_y() + 2
        except Exception:
            pass

    # Company name
    pdf.set_y(max(y, pdf.get_y()))
    pdf.set_font('Courier', 'B', 10)
    pdf.set_x(left)
    pdf.cell(page_w, 5, company.get('name', ''), align='C')
    pdf.ln(5)

    # Company info
    pdf.set_font('Courier', '', 7)
    info_lines = []
    if company.get('street'):
        info_lines.append(company['street'])
    city_parts = []
    if company.get('city'):
        city_parts.append(company['city'])
    if company.get('state'):
        city_parts.append(company['state'])
    if company.get('zip_code'):
        city_parts.append(company['zip_code'])
    if city_parts:
        info_lines.append(' '.join(city_parts))
    if company.get('country'):
        info_lines.append(company['country'])
    if company.get('phone'):
        info_lines.append(f"{_('tel', lang)}: {company['phone']}")
    if company.get('email'):
        info_lines.append(company['email'])
    if company.get('vat'):
        info_lines.append(f"{_('tax_id', lang)}: {company['vat']}")

    for line in info_lines:
        pdf.set_x(left)
        pdf.cell(page_w, 3.5, line, align='C')
        pdf.ln(3.5)

    # Dashed line
    pdf.ln(1)
    pdf.set_x(left)
    pdf.set_font('Courier', '', 8)
    pdf.cell(page_w, 3, '-' * 70, align='C')
    pdf.ln(4)

    # Receipt header
    pdf.set_font('Courier', 'B', 12)
    pdf.set_x(left)
    pdf.cell(page_w, 6, _('receipt', lang).upper(), align='C')
    pdf.ln(6)

    # Dashed line
    pdf.set_x(left)
    pdf.set_font('Courier', '', 8)
    pdf.cell(page_w, 3, '-' * 70, align='C')
    pdf.ln(4)

    ref = data.get('name', '') or f"{_('order', lang)} #{d['id']}"
    date_val = (data.get('date_order', '') or '')[:19]
    state = data.get('state', '')
    total = float(data.get('amount_total', 0) or 0)
    delivery_cost = float(d.get('delivery_cost', 0) or 0)
    items_total = total - delivery_cost
    paid = float(data.get('amount_paid', 0) or 0)
    change = float(data.get('amount_change', 0) or 0)

    # Order info
    pdf.set_font('Courier', '', 8)
    pdf.set_x(left)
    pdf.cell(page_w, 4, f"{_('order', lang)}: {ref}  {_('status', lang)}: {state.upper()}")
    pdf.ln(4)
    pdf.set_x(left)
    pdf.cell(page_w, 4, f"{_('date', lang)}: {date_val}")
    pdf.ln(4)
    pdf.set_x(left)
    pdf.cell(page_w, 4, f"{_('cashier', lang)}: {d['user_name']}")
    pdf.ln(4)
    pdf.set_x(left)
    pdf.cell(page_w, 4, f"{_('customer', lang)}: {d['partner_name']}")
    pdf.ln(4)

    if d.get('delivery_contact_name') or d.get('delivery_contact_phone'):
        parts = []
        if d.get('delivery_contact_name'):
            parts.append(d['delivery_contact_name'])
        if d.get('delivery_contact_phone'):
            parts.append(d['delivery_contact_phone'])
        contact_str = ' - '.join(parts)
        dz_name = d.get('delivery_zone_name', '')
        pdf.set_x(left)
        pdf.cell(page_w, 4, f"{_('delivery', lang)}: {dz_name}  {contact_str}")
        pdf.ln(4)

    # Dashed line
    pdf.set_x(left)
    pdf.set_font('Courier', '', 8)
    pdf.cell(page_w, 3, '-' * 70, align='C')
    pdf.ln(4)

    # Items header
    pdf.set_font('Courier', 'B', 8)
    col_w = [28, 8, 18, 16]
    headers = [_('item', lang), _('qty', lang), _('price', lang), _('total', lang)]
    pdf.set_x(left)
    for i, h in enumerate(headers):
        pdf.cell(col_w[i], 4, h)
    pdf.ln(4)

    pdf.set_font('Courier', '', 8)
    pdf.set_x(left)
    pdf.cell(page_w, 2, '-' * 70, align='C')
    pdf.ln(3)

    # Items
    for line in lines:
        ld = line['_data']
        name = line['product_name']
        qty = float(ld.get('qty', 0) or 0)
        price = float(ld.get('price_unit', 0) or 0)
        disc = float(ld.get('discount', 0) or 0)
        subtotal = float(ld.get('price_subtotal', 0) or (qty * price * (1 - disc / 100)))

        pdf.set_x(left)
        pdf.cell(col_w[0], 4, name[:18])
        pdf.cell(col_w[1], 4, str(int(qty) if qty == int(qty) else qty), align='C')
        pdf.cell(col_w[2], 4, currency_format(price, currency), align='R')
        pdf.cell(col_w[3], 4, currency_format(subtotal, currency), align='R')
        pdf.ln(4)

    # Dashed line
    pdf.set_x(left)
    pdf.set_font('Courier', '', 8)
    pdf.cell(page_w, 3, '-' * 70, align='C')
    pdf.ln(4)

    # Totals
    pdf.set_font('Courier', '', 8)
    pdf.set_x(left)
    pdf.cell(page_w - 20, 4, f"{_('subtotal', lang)}:", align='R')
    pdf.cell(20, 4, currency_format(items_total, currency), align='R')
    pdf.ln(4)

    if delivery_cost > 0:
        pdf.set_x(left)
        pdf.cell(page_w - 20, 4, f"{_('delivery', lang)}:", align='R')
        pdf.cell(20, 4, currency_format(delivery_cost, currency), align='R')
        pdf.ln(4)

    pdf.set_x(left)
    pdf.cell(page_w - 20, 4, f"{_('discount', lang)}:", align='R')
    pdf.cell(20, 4, currency_format(0, currency), align='R')
    pdf.ln(4)

    pdf.set_font('Courier', 'B', 9)
    pdf.set_x(left)
    pdf.cell(page_w - 20, 5, f"{_('total', lang).upper()}:", align='R')
    pdf.cell(20, 5, currency_format(total, currency), align='R')
    pdf.ln(6)

    # Receipt header text
    if company.get('receipt_header'):
        pdf.set_x(left)
        pdf.set_font('Courier', '', 7)
        pdf.cell(page_w, 3, '-' * 70, align='C')
        pdf.ln(3)
        pdf.set_x(left)
        pdf.cell(page_w, 4, company['receipt_header'], align='C')
        pdf.ln(4)

    # Payment info
    pdf.set_x(left)
    pdf.set_font('Courier', '', 8)
    pdf.cell(page_w, 3, '-' * 70, align='C')
    pdf.ln(3)
    pdf.set_font('Courier', 'B', 8)
    pdf.set_x(left)
    pdf.cell(page_w, 4, _('payment', lang), align='C')
    pdf.ln(5)

    pdf.set_font('Courier', '', 8)
    for pmt in payments:
        pd = pmt['_data']
        pmt_name = pmt['payment_method_name']
        amt = float(pd.get('amount', 0) or 0)
        pdf.set_x(left)
        pdf.cell(page_w - 20, 4, pmt_name, align='L')
        pdf.cell(20, 4, currency_format(amt, currency), align='R')
        pdf.ln(4)

    pdf.set_x(left)
    pdf.cell(page_w - 20, 4, f"{_('change', lang)}:", align='R')
    pdf.cell(20, 4, currency_format(change, currency), align='R')
    pdf.ln(4)

    # Receipt footer
    if company.get('receipt_footer'):
        pdf.set_x(left)
        pdf.set_font('Courier', '', 8)
        pdf.cell(page_w, 3, '-' * 70, align='C')
        pdf.ln(3)
        pdf.set_font('Courier', '', 8)
        pdf.set_x(left)
        pdf.cell(page_w, 4, company['receipt_footer'], align='C')
        pdf.ln(4)

    # Footer line
    pdf.set_x(left)
    pdf.set_font('Courier', '', 7)
    pdf.cell(page_w, 3, '-' * 70, align='C')
    pdf.ln(3)
    pdf.set_x(left)
    pdf.cell(page_w, 3, _('generated', lang), align='C')

    # Return as bytes
    result = pdf.output(dest='S')
    if isinstance(result, bytearray):
        return bytes(result)
    if isinstance(result, str):
        return result.encode('latin-1')
    return result
